const types = {
    LOAD_TASKS: "LOAD_TASKS",
    ADD_TASKS: "ADD_TASKS",
    LOAD_USERS: "LOAD_USERS",
    GET_TASK: 'GET_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    TASKS_RECEIVED: 'TASKS_RECEIVED',
    USERS_RECEIVED: 'USERS_RECEIVED',
    TASK_RECEIVED: 'TASK_RECEIVED',
}

export default types;